from wordle import Wordle
game = Wordle("data/french_dict5.txt")
game.add_hard_constraint("t", 0)
# game.add_hard_constraint("o", 1)
# game.add_hard_constraint("r", 2)
# game.add_hard_constraint("r", 3)
game.add_hard_constraint("e", 4)
game.add_negative_constraint("a")
game.add_negative_constraint("s")
game.add_negative_constraint("u")
# game.add_negative_constraint("l")
# game.add_negative_constraint("v")
# game.add_negative_constraint("r")
# game.add_negative_constraint("p")
# game.add_negative_constraint("o")
# game.add_negative_constraint("n")
# game.add_negative_constraint("u")
# game.add_negative_constraint("h")
# game.add_negative_constraint("w")
# game.add_negative_constraint("i")
# game.add_negative_constraint("u")
# game.add_negative_constraint("d")
# game.add_negative_constraint("i")
# game.add_soft_constraint("e")
# game.add_soft_constraint("r")
# game.add_soft_constraint("r")
# game.add_soft_constraint("e")
game.add_soft_constraint("i")
game.add_soft_constraint("e")
game.add_soft_constraint("r")
game.apply_hard_constraints()
game.apply_negative_constraints()
game.apply_soft_constraints()

print(len(game.data))
if len(game.data) < 100:
    print(game.data)
print(game.data)
print(game.optimize())
print(game.optimize(False))
