from wordle import Wordle
game = Wordle("data/french_dict5.txt")
len(game.data)
game.add_hard_constraint("i", 1)
game.add_hard_constraint("s", 4)
game.add_negative_constraint("a")
game.add_negative_constraint("g")
game.add_negative_constraint("l")
game.add_negative_constraint("n")
game.add_negative_constraint("o")
game.add_negative_constraint("f")
game.add_negative_constraint("a")
game.add_negative_constraint("d")
# game.add_negative_constraint("i")
# game.add_negative_constraint("u")
# game.add_negative_constraint("d")
# game.add_negative_constraint("i")
game.add_soft_constraint("e")
game.add_soft_constraint("t")
# game.add_soft_constraint("a")
# game.add_soft_constraint("l")
# game.add_soft_constraint("f")
game.apply_hard_constraints()
game.apply_negative_constraints()
game.apply_soft_constraints()

print(len(game.data))
if len(game.data) < 100:
    print(game.data)
print(game.optimize())
