from wordle import Wordle
game = Wordle("data/english_dict5.txt")
game.add_hard_constraint("s", 0)
game.add_hard_constraint("h", 1)
game.add_hard_constraint("a", 2)
# game.add_hard_constraint("e", 3)
game.add_hard_constraint("e", 4)
game.add_negative_constraint("u")
game.add_negative_constraint("d")
game.add_negative_constraint("i")
game.add_negative_constraint("o")
game.add_negative_constraint("t")
game.add_negative_constraint("g")
game.add_negative_constraint("p")
game.add_negative_constraint("r")
# game.add_negative_constraint("o")
# game.add_negative_constraint("s")
# game.add_negative_constraint("b")
# game.add_negative_constraint("l")
# game.add_negative_constraint("v")
# game.add_negative_constraint("i")
# game.add_negative_constraint("u")
# game.add_negative_constraint("d")
# game.add_negative_constraint("i")
# game.add_soft_constraint("o")
# game.add_soft_constraint("a")
# game.add_soft_constraint("l")
# game.add_soft_constraint("l")
# game.add_soft_constraint("c")
# game.add_soft_constraint("l")
# game.add_soft_constraint("f")
game.apply_hard_constraints()
game.apply_negative_constraints()
game.apply_soft_constraints()

if len(game.data) < 100:
    print(game.data)
print(game.optimize())
print(game.optimize(False))
